using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace HealthSystemProject
{
    internal class Program
    {

        static int health;
        static int shields;
        static int lives;
        static int score;
        static int reservedamage;

        static void Main(string[] args)
        {
            // time to assign values
            int enemyDamage;
            int enemyValue;

            int regularPoints;
            int doublePoints;
            int triplePoints;

            //- - -

            health = 75;
            lives = 2;
            shields = 100;
            score = 0;

            enemyDamage = 15;
            enemyValue = 10;

            regularPoints = 1;
            doublePoints = 2;
            triplePoints = 3;

            // simulated gameplay

            ShowHUD();

            damageCounting(enemyDamage);
            ScoreCounting(enemyValue, regularPoints);
            ShowHUD();
           

            heal(200);
            ShowHUD();

            shieldRegen(30);
            ShowHUD();

            liveCounter(1);
            ShowHUD();

            Console.ReadKey();

            // simulated gameplay

        }

        static void ShowHUD()
        {
            Console.WriteLine("{ - - - }");
            Console.WriteLine("Player Score: " + score);
            Console.WriteLine("Player Health: " + health + ", Lives Remaining: " + lives);
            Console.WriteLine("Shield Percent: " + shields);
            Console.WriteLine("{ - - - }");
        }

        static void ScoreCounting(int points, int multiplyer)
        {
            score = score + points;
            score = score * multiplyer;

            Console.WriteLine("Gained " + points + " points!");

        }

        static void damageCounting(int damage)
        {
            reservedamage = 0;

            shields = shields - damage;

            if (shields < 0)
            {
                reservedamage = damage - shields;
                health = (health - reservedamage);

                shields = 0;
                reservedamage = 0;

                if (health < 0)
                {
                    health = 0;
                }
            }

            reservedamage = 0;


            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine("You have taken " + damage + " damage!");
        
        }
        static void liveCounter(int lostLife)
        {
            lives = lives - lostLife;

            if (lives < 0)
            {
                lives = 0;
            }

            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine("Watch out! You just lost " + lostLife + " life!");
        }

        static void heal(int healing)
        {
            health = health + healing;

            if (health > 100)
            {
                health = 100;
            }

            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine("You have recovered " + healing + " health!");
        }

        static void shieldRegen(int regen)
        {
            shields = shields + regen;

            if (shields > 100)
            {
                shields = 100;
            }

            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine();
            Console.WriteLine("Your shields regenerated by " + regen + "!");
        }
    }
}
